### ISSUE TITLE
MangaWorld

### ISSUE THREAD

**Issue by Gannanan** [pandeynmn/extensions-foreign#1]
When you select a manga from "Manga del Mese" or "Capitoli di Tendenza" the paperback app crashes, and when it doesn't the manga appears with blank chapters

**Comment by Gannanan** [comment]
and also, when you look at a chapter, the release date is bugged and instead shows the seconds

**Comment by pandeynmn** [comment]
I did not implement the time at the moment but I will implement it soon.
I can't replicate the app crashing so if you could provide more info or a video posted on the paperback discord server, that would be helpful
