### ISSUE TITLE
MangaWorld's Source for Paperback doesn't work anymore

### ISSUE THREAD

**Issue by PerryEiji** [pandeynmn/extensions-foreign#9]
Hi, I wanted to ask if there was a possibility to fix the source of the MangaWorld site for the Paperback application. Thank you

**Comment by pandeynmn** [comment]
Hello, I am working on a couple of different things and MangaWorld is one of them, I'll try to fix it as soon as I can.

**Comment by PerryEiji** [comment]
Oh, thank you so much! I just asked why I hadn't been able to use it for 1/2 weeks and thought it wasn't in development anymore. If I may ask, do you plan to dispel the Mangaworld source for the Paperback v0.8 as well? Thanks anyway

**Comment by pandeynmn** [comment]
0.7 source should work on 0.8 versions as well, I do plan to update all my repos to 0.8 when I have fixed things I need to fix and have time to focus on the 0.8 update.

**Comment by pandeynmn** [comment]
All right, I updated the source, it should be live in a couple of minutes, let me know if something else is not working. I fixed the chapter images not loading.

**Comment by PerryEiji** [comment]
Great! Everything goes perfectly. Thank you very much, I'm grateful

**Comment by pandeynmn** [comment]
Glad to hear it!
